### ISSUE TITLE
how to setup when package.json and node_modules folder live within a subfolder

### ISSUE THREAD

**Issue by iuscare** [arvinxx/gitmoji-commit-workflow#75]
Hey, I know that this might be pure semantic release related, but I want to give it a shot here. Because of a docker setup, where the frontend part has its own container, I put the package.json and my other configuration files like webpack, eslint etc. into a separate folder called buildchain. Also the node_modules folder are being saved into this folder and npm commands are called within the folder.

Is there a way to let this setup work hand in hand with your gitmoji-commit-workflow? I've tried the working-directory for the github actions, but then I get asked about an npm_token. It is a private package, which should not be published to npm. Currently my workflow file looks like this:

```
name: Release CI
on:
  push:
    branches:
      - master
      - next
      - beta
      - alpha
      - pre/rc
      - 1.x
      - 2.x

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'

      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: install
        working-directory: ./buildchain
        run: npm install

      - name: release
        working-directory: ./buildchain
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

And my directory setup looks like this:
<img width="369" alt="Bildschirmfoto 2021-03-24 um 14 42 30" src="https://user-images.githubusercontent.com/33871309/112320342-3d448c00-8caf-11eb-84b9-87570b8eb460.png">

I'd still want to publish the package to a private github repo at once including a Changelog.md in the root level, I just have the problem that the package.json and node_modules folder live within the buildchain folder and I don't know how to setup gitmoji-commit-workflow properly to work with this structure.

Kind Regards!
